pycupiddb/__init__.py,sha256=EQpFeSHb1knGN0C2czsxxKOlWY5-WK70s7sNkuG_y3w,115
pycupiddb/client.py,sha256=lSZhaqKnlUY1Btvp2H3FIGly6XlAHHRmkgaxYd1_TF4,2067
pycupiddb/commands.py,sha256=cN3Gam0Ca5CSce39ga3ys0SYZUju7Cz9hRTqbDjXECE,7032
pycupiddb/connection.py,sha256=SJjCU7h6ItzMXea27fJF5EDfIU7P1b5SVNM34BKsNFk,7291
pycupiddb/exceptions.py,sha256=cRWU7f4cpSLw9yxsApieiBYOReDjJLQhUm_wjgyF6u4,228
pycupiddb-1.3.0.dist-info/LICENSE,sha256=1kJ9gvSe9DiFz_optTigubArvLORRTooqAzC3ZMyp8E,11342
pycupiddb-1.3.0.dist-info/METADATA,sha256=X6yrmBOiYOP4-Eeni08VQeq7fm_pibNlFqCaab1FLKM,14594
pycupiddb-1.3.0.dist-info/WHEEL,sha256=P9jw-gEje8ByB7_hXoICnHtVCrEwMQh-630tKvQWehc,91
pycupiddb-1.3.0.dist-info/top_level.txt,sha256=s7gc5nOoMjF7jBcWhh8miKs7Nth1w6cUFymDsiTZ0Bk,10
pycupiddb-1.3.0.dist-info/RECORD,,
