dataservice/__init__.py,sha256=gxmVwDx5MSOI5g5ab8BHeZdSLWCacoxXa-Ln-LDxDSw,820
dataservice/_utils.py,sha256=Pmdo-n1vt9VJImjQopVSxkMnYavpfDqms9BCg5WceFU,600
dataservice/cache.py,sha256=4gKcypCmdN1-aPrCsnXekp7w4xCy83oN4i-I8LUfevA,3688
dataservice/clients.py,sha256=-BxuPRqfYwVQe3AcXaPltYJmvQyB-dXta0FmpCMsnuo,8611
dataservice/config.py,sha256=uKS-eYA5ZioMuHbzf1lhtzY6zfc4fymPhpcsrILh6dg,2337
dataservice/data.py,sha256=VnqZElq8u2yeM5eksXqamDp_dirEpbh2Zgai96Gh4WQ,3898
dataservice/exceptions.py,sha256=2HqdX1gEM9SbLYaQX_Gyl3HnUkeQqeg0Y9ZNMA3xRUE,634
dataservice/files.py,sha256=ORiRtDtYBLaGnRQoXctOkMDm7q-C1HCnNxksihb6SBk,1999
dataservice/logs.py,sha256=2POOuBvIhHnp6R7e8eXRjt9mHPJthrj41cmRieXMmmU,1311
dataservice/models.py,sha256=H1rpxNBnu9-mMOgw-OoBRySRWYkaADYT9vRx9wLINNQ,5210
dataservice/service.py,sha256=fm3EZTmuIjdApNebHTfBdxt6pp-kF_MTRL5wCPmVxvM,3126
dataservice/worker.py,sha256=AVZOV63yKRDC_QaxghBGTtIoqjtolJHJfx14WwEjzBM,12600
python_dataservice-0.4.0.dist-info/LICENSE,sha256=YFuh1Fs-GEiQo-dmT_kAULdSQp9PNIda3yXzZIvCs8w,1068
python_dataservice-0.4.0.dist-info/METADATA,sha256=el9t14W-vAN2Yuv_DpujG0vhOqA-oMkZ7dwfEbs0X0Q,4202
python_dataservice-0.4.0.dist-info/WHEEL,sha256=Nq82e9rUAnEjt98J6MlVmMCZb-t9cYE2Ir1kpBmnWfs,88
python_dataservice-0.4.0.dist-info/RECORD,,
