valclient/__init__.py,sha256=XgVCHLt-zuVRJMU3DDk81vrXpoP1jpmEA8nXYRM210w,80
valclient/auth.py,sha256=-E4Uo3L_Fq79e5ajkNBbND1m_7N1b96LSSU_avgl85E,1688
valclient/client.py,sha256=cZkRBF1KztOF_eIJXWzwqQ_5mbLsqafRRnAtg4v6H3o,37222
valclient/exceptions.py,sha256=eh7_2sF6rwOrjeXi1eqojf-JFNzGbMbvm_asJ2ET22M,648
valclient/resources.py,sha256=6qHLfmUAvrx2d6kUrewqsyx7A_dXU6SKtWemzgwWTrE,503
valclient_remake-2.28.dist-info/LICENSE,sha256=DMa0S4kCF2Rv3ZpFvCjfJrgdDQb-yWzQJFyLtQ3X1HA,1083
valclient_remake-2.28.dist-info/METADATA,sha256=4fZmmX37yGMlFehfD8Xt8iQBpydQxKnt8CgVezZ9yR0,912
valclient_remake-2.28.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
valclient_remake-2.28.dist-info/top_level.txt,sha256=My3MYDwjDCsZdk6p0iwIofBIP6VMj8DcW1yeWCfAdwc,10
valclient_remake-2.28.dist-info/RECORD,,
